//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanadaTrustv1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageBoxText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageBoxText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CanadaTrustv1.MessageBoxText", typeof(MessageBoxText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please consider rating and reviewing this app. Plese tap &apos;OK&apos; to be taken to the marketplace screen.
        /// </summary>
        internal static string ConsiderRating {
            get {
                return ResourceManager.GetString("ConsiderRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate and Review.
        /// </summary>
        internal static string ConsiderRatingTitle {
            get {
                return ResourceManager.GetString("ConsiderRatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently, this app requires location services to function. If you would like to enable location services, you can do so from the settings menu..
        /// </summary>
        internal static string EnableLocationServices {
            get {
                return ResourceManager.GetString("EnableLocationServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently, this app requires location services to function. If you would like to enable location services, you can do so from the settings menu..
        /// </summary>
        internal static string LocationServicesRequired {
            get {
                return ResourceManager.GetString("LocationServicesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Services Required.
        /// </summary>
        internal static string LocationServicesRequiredTitle {
            get {
                return ResourceManager.GetString("LocationServicesRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is not available in your location/region.
        ///Please try again later..
        /// </summary>
        internal static string OutsideOfCanada {
            get {
                return ResourceManager.GetString("OutsideOfCanada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside of Canada.
        /// </summary>
        internal static string OutsideOfCanadaTitle {
            get {
                return ResourceManager.GetString("OutsideOfCanadaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem connecting to the remote location service. Please check your internet connection and try again..
        /// </summary>
        internal static string ProblemConnecting {
            get {
                return ResourceManager.GetString("ProblemConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Services Problem.
        /// </summary>
        internal static string ProblemConnectingTitle {
            get {
                return ResourceManager.GetString("ProblemConnectingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app requires use of Location Services data. Please tap &apos;OK&apos; to give your consent..
        /// </summary>
        internal static string RequireLocationServices {
            get {
                return ResourceManager.GetString("RequireLocationServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Services Consent.
        /// </summary>
        internal static string RequireLocationServicesTitle {
            get {
                return ResourceManager.GetString("RequireLocationServicesTitle", resourceCulture);
            }
        }
    }
}
